---
- name: Setup dnsmasq config
  action: template owner=root group=root mode=644 src=etc/dnsmasq.conf dest=/etc/dnsmasq.conf


- name: Enable dnsmasq
  tags: networking
  service: name=dnsmasq state=started enabled=yes

- name: Setup DNS
  action: template owner=root group=root mode=644 src=etc/resolv.conf.upstream dest=/etc/resolv.conf.upstream


- name: Resart dnsmasq
  tags: networking
  service: name=dnsmasq state=restarted 
